import matplotlib.pyplot as plt
import numpy as np

weights = np.load('weights.npy')
weights2 = np.load('weights_2.npy')
weights3 = np.load('weights_3.npy')
weights4 = np.load('weights_4.npy')
weights6 = np.load('weights_6.npy')
weights5 = np.load('weights_5.npy')
weights7 = np.load('weights_7.npy')

plt.figure()
plt.plot(range(weights.shape[0]), weights)
plt.figure()
plt.plot(range(weights.shape[0]), weights2)
plt.figure()
plt.plot(range(weights.shape[0]), weights3)
plt.figure()
plt.plot(range(weights.shape[0]), weights4)
plt.figure()
plt.plot(range(weights5.shape[0]), weights5)
plt.figure()
plt.plot(range(weights6.shape[0]), weights6)
plt.figure()
plt.plot(range(weights7.shape[0]), weights7)
plt.show()
